# Generated by Django 2.0 on 2018-01-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=60)),
                ('cate_name', models.IntegerField(choices=[(1, '美团外卖'), (2, '饿了么')], help_text='分类', max_length=20)),
                ('url', models.CharField(help_text='url', max_length=120)),
                ('click_count', models.IntegerField(default=0, help_text='点击次数')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间')),
                ('last_click_time', models.DateField(auto_now=True, help_text='最后抢的时间')),
            ],
        ),
    ]
